
spring:
  application:
    name: spring-cloud-turbine

server:
  port: 8023

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

feign:
  circuitbreaker:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"


turbine:
  # appConfing配置需要聚合的服务名称，比如这里聚合自动投递微服务的hystrix监控数据
  # 如果要聚合多个微服务的监控数据，那么可以使用英文逗号拼接，比如 a,b,c
  appConfig: spring-cloud-dashboard
  clusterNameExpression: "'default'"   # 集群默认名称




management:
  endpoints:
    web:
      exposure:
        include: "*"