
spring:
  application:
    name: spring-cloud-consumer

server:
  port: 8021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/



feign:
  circuitbreaker:
    enabled: true



